apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sentry
  namespace: sentry-system
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - sentry.ops.last-try.org
      secretName: sentry-tls
  rules:
    - host: sentry.ops.last-try.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sentry-web
                port:
                  number: 9000
