apiVersion: v1
kind: Service
metadata:
  name: valkey
  namespace: valkey
  labels:
    app: valkey
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: redis
      name: redis
    - port: 9121
      targetPort: metrics
      name: metrics
  selector:
    app: valkey
