# kubernetes-replicator values
# Replicates secrets/configmaps across namespaces

replicateSecrets: true
replicateConfigMaps: true
replicateRoles: false
replicateRoleBindings: false
replicateServiceAccounts: false

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 32Mi
