apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - storageclass-single-replica.yaml
  - storageclass-replicated.yaml
  - storageclass-ephemeral.yaml
  - backup-secret-sealed.yaml
  - oauth2-proxy/deployment.yaml
  - oauth2-proxy/service.yaml
  - oauth2-proxy/cookie-secret-sealed.yaml
  - oauth2-proxy/ingress.yaml
