apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: sentry
  namespace: sentry-system
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`sentry.ops.last-try.org`)
      kind: Rule
      services:
        - name: sentry-web
          port: 9000
  tls:
    certResolver: letsencrypt-prod
