apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: glitchtip
  namespace: glitchtip-system
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - glitchtip.ops.last-try.org
      secretName: glitchtip-tls
  rules:
    - host: glitchtip.ops.last-try.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: glitchtip-web
                port:
                  number: 80
