---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-env-configuration
  namespace: minio
spec:
  encryptedData:
    config.env: AgBHef63//PIKErZzTGyb7jyT/RFfRxhHAgRP7kweMCmdY4xp2JJxfrJFE65n+vKJ058DyNhnOR9Qlc9nU8nqr6AwKyiuG+Xr4AirOP+AeyyhQVxOG5FkJslkIahJEapf+aIzqQVwMLirs5B9gu7OpE83NPRC2fxVvfRKXfLj6tzBGybIa403nmfG4AVr9Gp8wP8n7CxZ8rIxbTrJHIoAqy5mWFj0OM0JSc2KuLvmt/hBVDy0xdoF69ZqoM1YUXUtfFDmCIj0OLqimSo2R95b2PfMEEGLKeGnIv8cPxo5+X0OGRFi4gmEzvEG4gJk68iyJ6rVl+2TUAfcSOVmZI9kyx0rtkNPEPWwhxSPpSLFCPuCF0XL7GsBOxjmqSJ8617FAh0CaUk/umevrFoQkWK7njBjNNmytGpWfqUCP5K2ZS59SY3MS189Ixa78KO7TBZ01+Cpv12tkrG/uLa0gGgcdg6Oy0eUa0jYqjEP42OgiaXQ25zgfRrt+4v959bji9ltwI9dVdr+lBEn5l8Z7uo+Cxkh2T/d7M77OjOG9DOLaIS/cBejVk+O1dlAMdmOwQpq+ztun2z21npRcNIQpk70T9KtADaigLHX1OfzDw1tZjs8vuGTgBZou1m/vJ+9Qv4S59Bs5jU0CUg3m6yheuIroEYKU8SufocGxbUaX4QVR9if1yP/en78blQs21Yt+n89ElC55wQo9/G2Iw0spFAzRynsdXCKuWYTSvLmR+RW8bQMQp7svctMxGh6bBNYNZf40MxIGHFr3431Ql8b8G12IkE4BlDgvL3X3y0pNhy6y5NtOF9PLaBtS/UOvlJLGU8J9amHXGo3ZLXCRw=
  template:
    metadata:
      name: minio-env-configuration
      namespace: minio
    type: Opaque
