---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: oauth2-proxy-alertmanager-cookie
  namespace: monitoring
spec:
  encryptedData:
    cookie-secret: AgAJG8hI7klGY1sHVrMP8RCjgoRseamHtLEXpTFCo/Yfl/aJIg4my0imSaP6EWdbORWDDWjGWEmMeP/UjMklTDx6vduAWm4zbSlKiGlXssLzSbmJTapBW1U6bM7KkUOfsfmfJ9muQpUpBo/YjzaOvEad86c3Igp7zfCL3LRpzEnpbzT5ZZqrY9GYwUQSdIeOpJY/tbN6FA1Maj0Vnsmsb01112YOK2DmHoGtWq3xgnRl82w0cVRUicizgob0GbIkgSLYCg4/+vEZGg6kpxR1mjSC2FYFbRk/gFjmjf9CdDpoyuZ71PRZ8yscxzyO4MyNrIZGEw69/nTmd/DJIigHaoG9siNgXGvY9JSOraSMOIiteausMvO8wumpnbiMtCTvwS6Csukm8v2mEt1plY+mBaXyFP1HRV3ZhsHP9EsQ6uMw1QTOPFAJY8QUgchhjopUvmeXgXEKzuYxgVEn2w7IOh2mE4B0kSiskkmnYL8ZL67r0pPjU2nOahMX/5zfoGEACJnYvCDgwcNzdhOcy0ff4vk4mJUg2lnFaXbivf7vbEX8nXc5YjWNQZ3/aD8yz3Uw7ZzFYTaHy8hnCJ4BC7MTRu0vqEQIKROjtomZSYI5NwZt4DgPF8ARVq0sbkNaCYRhpkLKtnlX8/MRafKrnjgRzCNidC9ETulk8gVB/OCflVvVjQ2X44P/+FNXZpSSh27L4xgin5ercwZk3L4BIKp2JorgenfpVY5fjuyu4s6biv6fUQ==
  template:
    metadata:
      name: oauth2-proxy-alertmanager-cookie
      namespace: monitoring
    type: Opaque
