---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: oauth2-proxy-alertmanager-secrets
  namespace: monitoring
spec:
  encryptedData:
    client-secret: AgCjPNdZNjPZhdpRAKI7TmXWKEMIVSm+X9nKZuLD8F3ok+56lC1e34NhH+dm+nUPV9J+UrQ6+Rr2s6BGKmjl2HWPb2f9pJ0nvDtxkxcrnyG0nzJ2z6zlhzDqup/U/bhWBcEicaK6FCGck0dR4aPGy7Z0s2+EHiNKLeFzrcWCnhRSIFXfrIps2PJZA7kwk8VldIFAlxch+4xCtDZVa6FO2o/1JISARSoPXrLBNYLaHgGyIB3yP6e7uOrX0ZmZqUeVtGi3MnahuwRGmhN6CRhETXMiNA9WIn5ZqM7r90uS2z1mFmqnw5GJiz/LfrN7FTKAFAI3JOje5+wnmKN8mUODQzK5ATYABWVTfsYf/YtcErrjr96wAqJnY/qXNRl2P+xhEE5v8QA/QxeS8gUWplVtRUOd0t1tuT8dk4fylCEX/ZUHttfJFRKd4RH2s85Nw+Umu+s98OHd7Ik3d+rO2KEtsM7x8oqG1YK8e3OGSi33Adqh2sNJWLQcWeeb9zM0Ub/zmzIVCZjLdUA8E9UMNpE3zLEE6kD/dR2UMLXIvQMsM767vfpBUxg1moafJt4WkkGtEq3E2w58SW+9DisxJJsGRMhFx+3WpbmuoMlf5IS7/pF4i5Lumz96n1qUKB5l0/9KX3jEZDE/y7FLYtbg1cUrJpJ7vVXnT7pLFAsm5AJFca8qtuXyNE8fG7CXYZrEghCf38lFeUmDW31ksuzbZdNR242P/+0XcU1Bld+/ZrXzDsbS98RL6Fu9HYdug+ahwV3h7iui7ZBaC6kdZI0Mqfu8Ibhz
    cookie-secret: AgBiz046AXorUnPzWoExcAOsf+3BJB4f5uCsRP0qbGf9874yZHmIOkepwqO3m9DdkWkcS6ojjXQbxAHAY9KSO5sjO5ilXpOQHpTa4Ova7g1dqzAK+YNVbkFRUhfdeGPmpubnA+CgIajb3q4bvVb/BnOVC65q6ayS7/JR5cWl7R+r0pR19zTwF/CFJKJe2xdhHlILbyDuAgc/bvdgzg6qs2cC2rCtOsVSvGxxBMlTsSXOXwt4lEcSfanAX48bGM68P0ELQn6p9eV7NQX3RKBz4gLbSVPY+eS/7w6rHg3xJNSBnO9lggf9VUThdRTJ3Fwtt711z4EqXzK3nYupLa9ebYxe5Mvx9uhG9J6DzTkpEhNBTG7bfzIE3Ddtd1D0oor1RlWYbZpd/0dRKVBiVNCFAFkPLZ3IXlz3hupmX0WzudPlPvpqsCXMqz72rhkZ+FRuXmG4Wm7cIIC3trNfclJ6Wdmj4tmjFDz0rljdfloeekup6uSmHgWuvvcx5xhZQx1wc6Lzwr4Y5ksp9pd1EifWlYCVRHeT7oPTuiPzGibDWTi6Suavr67J7dhjtf0xWifVBI6PvRJa8ekL5aB2r11PEt1ZD5WRGz9CFiTLH1fBc/AV3sVYmhkG1fEngldHiA539JTolmjKvmh/rqnIWvAuy1q5DVtoKVFe7qnIwdvUppHvpr8MXc7xoZnO+pZ3LULmnDoB0wcmCaSfoc90V7ZubS8nyrdViEH7w/0742gTnj2vVQ==
  template:
    metadata:
      name: oauth2-proxy-alertmanager-secrets
      namespace: monitoring
    type: Opaque
