---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: oauth2-proxy-alertmanager-secrets
  namespace: monitoring
spec:
  encryptedData:
    client-secret: AgCQz9IplzewE0XRLJUorwcgtjP9lFlLGWveO+lkDTC7tcvwvnmbCjGgH7MJwlSBeQl/LUHbdQRtXTs98aVfcvzB4sYAUGLwgMbX3J4thHD7vXbo+Iqg0ClNAoz8gqIaR0ODoPrE1fCaQfNop1CvfscGdtLTUx6YelzuYEet3XnHhyJ/EDdwigGUluoXzuY8Zzlma4yJa48pHj6v5UObzEPR1cR/PNNCL21GLlXPQNSm8Vk2GiwwpZ00BNqyAKXx5xSJsYE9FDpeZYbX3ACgv34QK9114HtqS5mBrAmf8j90HgjHOfEdZfK0URC3saL6nSdQ5v7PzMHKPgshvy5GCYLSPAtsphHQ4FpkHheRtY4TxLz2Zj94jRM+UgM61L7Skd2xUal59A3pSv484GFwp+f6kYPla/QR7wBJ3+vi9UIcrnV18NEhQZuW9EsD8uI4bg0brz9t5uCVsypCC7jqeyfbGBCU/ty39U7+qwbtIKR1vfvc2nzm7XsHOwcjnM2HLUx9CtXg9mBOY8VgeuSLtL4bosjbWGznJfXrLyzO4llSFMMQcGsMbH5JdKzL0ViGdYzbazVj79R6fGT5+0NJJN5YbqiRSNuAa5YR9CZcHseSQozfsFOeqZNv5ahKVdNXNLlz5nNwY480a7J9QguYKC6geor1Zgn0SU4tyTp5b5Vtg1KpG6pzgQTop8Hy7ATnfX3jw2nzwpwX03LJcfEhYqlVHZW7nvogZ+BGnltdVLR5K3+4Kd/Dqk5pthA4Nw==
    cookie-secret: AgAJaT3hiMc+p5Qp90L9uKA7k3pBh/USefnCPBXAX3x+XcUHHagTu8xG5EJ7oN13y+TzeqmsPE0Mf7yS5sseUZBjbzLuU+0mPQ62N+6DzkSHwsV8XiA12qVVkKL4a+zewZF6CdORIxm9yk7tXaA9tS6/KqwA26Ui10PPkLNGrBrYOSAUuoqkXZojLVx3rs5AY8r7YxEXcAbFfdAia5GBeFKl5SP7u/GLIsdoIlFNsb5iNgWf/rXni9KXMFO7tT10uvuUokGTCPpFlo1hsQw7rys1BmlnI61JLIN8e7mJrirqwvLdw3YSvlVk1AD4LCZVgpYB3Ek4DlAps2m9vRXGKXgwXSYuE8MM9cn6GEE3mDnbsEpxWxpa0bBk2BF+mu2xIhPZlbn0P+vEvbzjRXqe6Ex56Lqy/RvrEQUJUNxusysyQrdBWnigsQvPsHbRGiHC/POkkIletusCHfHY5aT7XAv/6GaW690HyE5qr1+ABbsJFxX7rHkK5DOOkURSW+jloY1VXEuxrdISdnMC4w2TVNgJYEgO30kfk5iL5p23Fooktn4cz/Rze1alWrnGmbwSIYBojd6D+Lfkp0f1XnB4KRIbR9So9KTquutkI7tYoXG0ebTPgnmzeVHB867BmHywwVnFyfgwh0m3v/LkxZA9WMKMbpVbvOlWmXhlcrHOD429I71VDhJ6EU/Myv4ql88C0rYLgRO3FIYRAD6a00dumc+DHupnzCpLqr1gXy1tWHlN4Q==
  template:
    metadata:
      name: oauth2-proxy-alertmanager-secrets
      namespace: monitoring
    type: Opaque
