apiVersion: v1
kind: Service
metadata:
  name: gitlab-valkey
  namespace: gitlab
  labels:
    app: gitlab-valkey
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: redis
      name: redis
    - port: 9121
      targetPort: metrics
      name: metrics
  selector:
    app: gitlab-valkey
