---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-discord-webhook
  namespace: monitoring
spec:
  encryptedData:
    url: AgABK3eIhNEdS2c0h4c1QR58WCjeBxwYqJAgV+S4U6HE/fgJpuEC79IOH2wQd8qYKjjbYbH7+SpZ9rPnFq3SBBMM+VaAUZHTtOwgJW5gbFdI9BxqWcc+4qn0a3K7kV8lg6mL6s+11djpdb1OPWFgl63V4beQTu3dIxxLHlXg73GJadLjuwxyUU/qXD54u2BnFEMTVKwtJiCc+tz8sXKCMKdGI6s4YZSKa4qVLSV30f2htrHvAEUwnyga4aROk8yCE0wtuettY6JtITo6C2aRxVWHiQtvZK97QOG+yk442umfO7wKJmqTjvB/Rq8xLgCNb10sKT71QqNZPeSK4blZiHeasiR6wGkC4DUiKoHV8FK5QojTHj5AJk0ataeQ87epksjN3T6SLxEc54ot2rynWURi6oRQN2naei5FoVUejl8nXGMCoaXhCp53EQMurPCwDuMnn2BP4JzYoEDb3CZ0UqPQe36lT6EHrzV80c6n2H2RgRJaknsIrNYGUqfqFdade/t8Dyf0fm4M3+1zG/Eak2b9UlCCrLPIvrYTbltoYsAdQs6JT3xCQVM51KwzxcNBkwbyNzruJ7Asl1+lyxbuOORDx+Cil8Bp4Kc0H6bg/IznKYr+aT0Mg6eNl0rgiJ1gDRkBE8AfY73tbNBWACP+/VckdlYkImzHVl29TuWM20NgRIBt0DnN8LKmswxkr1esCYhMSq4m2MUUsZJFiXxM1w174B9g8Lkbty2ZaAJeaDqa5cnmor47QlWWi2cnml638luumpzww+lQA6S1fKs1vMN0dyDuKqALguj8L1+cGNDEXFFqtyof98Y2/un7UIpBcKNyFMGJokappbL1xUfN2A2K0uuw/UgITNM=
  template:
    metadata:
      name: alertmanager-discord-webhook
      namespace: monitoring
