---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: oauth2-proxy-prometheus-cookie
  namespace: monitoring
spec:
  encryptedData:
    cookie-secret: AgCQPFEeIZikzxP6TSKXAHY7TLjJHjoLWVVjuutW8RUuPWDQVHcDx0mrOqzILmKXGxoz9Cn13KrlPdgViA1y/7uy/2VLj0NiTxOlhrgeENWloHp79qYIwSa2ydqcyziFK7vVO86BpLatGpYvkt31MVwPFUFpZQdTqLCEQJxfGq/etrKi3mYkJQFhNi9kVeeW6mUCNsNpQRP4XKFK1Mh/WxIEynMk0uhJTZL8qpiNtJwXZeeFHjxikcMgE4Eb7DeSsbXTh84ukIOEY5tgtj/RLgw2cSRiOfbEDlzu3wAXhiVbLPiDnMDgTTGnvAimuSgJlMBJQRgI/339cj114q9YXhRZVUP2fW6owFE6o6iZKeMwwahR5NQnABWH9czgdDlvh11bVmy9nHwbXjqkFJnlyMKmzlW2DfHRIURiO63ey4vEKGwiIn8R1S3dexGNBlnnLVYouZ2EBgnj3RtMJNfjWb16mvfSROwld2F9gGFOAAoz8fM6epw0cHdRqTBVq8S5oIv6/HzC02PiQENxNjQyefvNZlzosbdj3EfT+6M6as+96hMvlCn/VXCI8BShsrkkFfD8M2TkSGvu5yC9w1s+HSzbrVBjcKdBr+8VFkkytGgpAdxlER/Wht1RyoF0YdTk4Tk2UD72ngx9XLiIgS4xMh8nwj9yyZaAafEg2iM3Oqw90+6e3bV/Nfwtt35I+gnarF7fnwyCUZrKnSf+bBSpTNyYCzwN792ANojncTSckDYo8Q==
  template:
    metadata:
      name: oauth2-proxy-prometheus-cookie
      namespace: monitoring
    type: Opaque
