---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: oauth2-proxy-prometheus-secrets
  namespace: monitoring
spec:
  encryptedData:
    client-secret: AgAsPXrifnq1TwE7mfDGK7Tee5tWP6kuFeptlDR9z3Lwrf5K8nMQU9TakGTch90JCy2MIOuEVp923C2NTs7XS2gGcx5+azrOz9lq/mlkrbNjX9eQCk8rxycqXex/5QRYG3jrAuVT8dScWcn0nIexNWglxXknIR+YBBd2IPMC9+34kCzgS+6yHsJ0UzVFewl1nYfRy5B/gZsJ0zkJpKCQcbY2nnoUu+nav1ZJKB7BpNATjaFlp/TEwDnBuZIFrHwerezx8mPva2mdXtLDrOWed41RFsRU/uLx1+iF/uQ0ppvmXhZd3dudZIBm3EResH14WJx2Wxo8Pn7cJKrMe3h/GW2Tl39br/81bTAUKmERfTg//NF05x8ju66TsRBrYetk/FvqGVpctZ8k4PjrzqgDZDrwMmJTetY2nfncarwGSYCif7NG1ZTPmzzifEJQtJm3UCJRKIoexZ0JforuOBiEpaBxx4DmeIlGsrL2joq/vh6K154Rjnet6n/pTAdCr3Kqu2wvuZY86r+mJVZvvsVh8FRjKosWUKJ8LqP6JnZLgmGGFVme9c79UHrs9v3RSXanzCF4dU13lB8eoYEYMf6VqXkKUxQwEjdPafLPjKnfx9mlC6LrseLFAMM/jKg035GaNIyl4pjouFgww/ZxUq6uUW1amCCCcw8iIxpz8CYesHh63hWEPIt4KBVgyxcYqeL5kI6ZJnJJ40sLAhE16gj6qmAvAV9HH6UNRja61/F5cLOjZi8yS5eaqb/cU8kj5xa9Gn2R6n69JTVgolOClyc9AOg=
    cookie-secret: AgANnUpjtv6ktdctzFsfF9Yw+IblUDSxgpKLLElbC8f/4lBFlUNjEALGsa2BnXktSs3xiJDOjXyhxRrr/whvIIp0Lm8Oa/Q/5n4xS2+9LxhAnjKIgCVBKToQrPsjcKxvZgs0ruuyFOqiXTg39gf5ImeJYJj0ETL+jTu1I57mIA3w/oRj3DB3gF1OwiEuNC19NxjnlxtTLLXvUKYtjtDOoEIoL+KXmsZhsMhs2c1v80dXifw8+/R4sqrBKHGCgtT+FsunYR5vM+qvwBa8lNM8+FfKgsFawyBtxd/FP5mwgWdEuW0f0akrFyU5pNAoKAqe42bXW1VgGtfbZNdfbIK1fZpQ33HbYQ14DJVUY3P4KcvGpmjZD9Pi3eeCL50knilYoSx14tmoxud654gV54btiKINha3C3tKkhWpFNCkkhB2za6rju/O8+ma7Pw1MkDcUQTNQ/U2EPozCe6qWUnhvojfueGrCr5oxi0gjyktSFQ1f/s8TuC06c4xxv8kv/5hDv/Hcvp7y8hWiE9NKsaOIbekW1AI3gt09jsN8UEHcheja5wa5pG4ptuWdSiBa7AgvxqX5CmyIKMPOXl421Qgfp9NMxjE4Cy7gJ8J4rA8D8Hb5MwZwjDBYPX8u1Mlfw+I5agaE1Z3M218Z6Vxwyr1fguiLdIZktUMKo3h8b5sHYAnpPHDfsjxDHQvFVnAeKlf03L8hLDUTsb3zPmYCXZB5434pOpm2NBaD/O9GxvBGhw/J1A==
  template:
    metadata:
      name: oauth2-proxy-prometheus-secrets
      namespace: monitoring
    type: Opaque
