---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: oauth2-proxy-prometheus-secrets
  namespace: monitoring
spec:
  encryptedData:
    client-secret: AgBB1ijRfvtf7rhP8+3+bPQOdLU0p1ifH5Hbi/qS/wEQb0mPykTVTjTV2EblEAv1qHM/W2AiFOVfjRV90OtPxl4+7PqtxkRj37oxgiDhRdTMnsI0QembfxA6hO3eCe28m9Y3Wy5oygBjy/P5ayXf+ajRMiE5x31y27fPs8f2uQjP9Qb+S+s+oLadYcdmaATjyCB4yyTklXJShfj69aizdwYvN/uMNJ+efsNhB8kg04vFne+lLslmNN3xMPZb07F6+85+FxBVwqv/vWpIzQmGHSBVnUOt5KmSJ7BradZFHDD32qnJh9cptOglb8gz+GRkOGQiEGOFncMkWD36/qpGEJouGODUThX/K8iAEWOj62ZakRUHmtkQiZLPdNXYwuCWE2A63iZi2g+yKGHKluPMmvRdhBpyOpJCe3llXR4mPkVVb1iJ8lEnFknBmX7WhTXJAxVN2rbA3ypiqfLqwXEm5b3qrhSi3xnMiARe1je3hpno1WsXY8RSqZDIZEPJoSC8oFNTd2DIU5VfBnRvh/iYOFE9OuxXNKGzVqNJ9l5YsEMGN3Yxjehq9sW3wUDKOw8Vuwbc80iwjIUdf/0MJrSckTCGc4tahW0Q82XocElPyEXQrISkjsIhZackOsc49TgzrTymBmWgw6ex8qW9oaIoBvFUlOKLgtyIi4onN/9NyFyjthZDwlRLRXACm39kGjzzFkCcNVPDchWjXqBUU1PkxRz2rwUvWu8oLSuye3mpRNyCGnKKO9POdmKKXE1a7rZaH/U4Q6yhYB6HCvNEBmZ7kFw=
    cookie-secret: AgCr//+npFo0a5cQIAhOndtr8OgmTloCtJOAfJt9PwJBkkX7NmCaaVaHfl/WyuBShzVHnYuh+QIYCpu1wvhuAlIv9VBIBQbUrG51nVyO2W5BZEHpRIeBrv52FNPOxc32Aru5mrQxHIocoynaluN9mqU2hX280DTQcmRZrrURjpwwyCqAqFHz3shAXqkEtjPbZg8GP+I0zctB1ld9Js1Xwu9O+6cuZ39RdqKsm6MwjNEIlHVUFlNtbMYU0kUmiFgHYu97wB/73CMn46A6g/YCCJQhWzsK1531//py9O1w2BM2mYior+00O3IUScvPwztZ9LUpnbslSuk9uGb3u5fELwCf8waaPJ8blu7i3C84d+kzTUe2Iylq4Z11LV3jrgk5hKgakVOeXu0qx5fSApncL1tryrgvmBH9b7M6epccACAkh7jlo7vshRNbS0t7RWRK8r/7AiT1HtXxU55SropdemSoQqWnwVrT47hzxhowvWFGNHnblf4ygt3wgvTHUull4sgtKtkp9VRXy94MAvgn75wxgZqUGhcBuiA7I1WC5dgxbp9x3B15O493IpdAJdWWwUUrWzkrthyAX6kMFppwBfU9pxWUFpIR0R8k1HghhF9wcw2Z7NiAelW5Ao753Z65dVOfb8eflnpbFwuyRAkHP/LHppp4UVNL8AqpBkgIfUMlcLGbF4hR9xLLKzddWCYVj/bT8xP5712bquiBt+qbpTGf8gi/YbTZSeXgYKJ4PSQ7mA==
  template:
    metadata:
      name: oauth2-proxy-prometheus-secrets
      namespace: monitoring
    type: Opaque
